---
- hosts: all
  sudo: yes
  tasks:
    - apt: name={{item}}
      with_items:
        - mercurial
        - ncurses-dev
        - lua5.2
        - liblua5.2-dev
        - ruby-dev
        - luajit
        - python-dev
        - python3-dev
