---
- hosts: all
  tasks:
    - name: (vim) git clone
      git:
        repo: 'https://github.com/h-east/vim.git'
        dest: '/tmp/vim'
        version: clpum

    - name: (vim) configure
      shell: cd /tmp/vim &&
        ./configure
          --with-features=huge
          --enable-multibyte
          --enable-luainterp=dynamic
          --enable-gpm
          --enable-cscope
          --enable-fontset
          --enable-fail-if-missing
          --enable-pythoninterp
          --enable-rubyinterp
          --with-ruby-command=`which ruby`
          --prefix=/usr/local

    - name: (vim) make install
      sudo: yes
      shell: 'cd /tmp/vim && make && sudo make install'
