---
- hosts: all
  tasks:
    - name: (vimrc) exist check
      shell: 'test -e "{{ansible_env.HOME}}"/.vim && test -e "{{ansible_env.HOME}}/.vim/install.sh"'
      register: exist_check
      ignore_errors: yes

    - name: (vimrc) git clone
      git:
        repo: 'https://github.com/MaxMEllon/.vim'
        dest: '{{ansible_env.HOME}}/.vim'
      when: exist_check|failed

    - name: (vimrc) install
      shell: 'cd "{{ansible_env.HOME}}"/.vim && bash install.sh'

